#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 
# 1,2,3,5,8,13,21,34,55,89,...
#By considering the terms in the Fibonacci sequence whose values do no exceed four million, find the sum of the even-values terms. 

fib_list = [1,2]

while fib_list[-1] < 4000000:

    sequence_term = fib_list[-1] + fib_list[-2]
    fib_list.append(sequence_term)

#gotta do this since a while loop will still append the last term if its over 4mill
fib_list.pop(-1)

even_fib_list = []

for i in fib_list:
    if i % 2 == 0:
        even_fib_list.append(i)        

print(sum(even_fib_list))
